version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: donishki
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: donishki
    depends_on:
      - db
    ports:
      - "3000:3000"